name: Publish Artifacts

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0.
        # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      # and https://docs.npmjs.com/about-semantic-versioning

jobs:
  publish:
    name: Release build and publish artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Release build
        run: ./gradlew assembleRelease

      - name: Publish to MavenCentral
        run: ./gradlew paho:publishReleasePublicationToSonatypeRepository
          :courier-core:publishReleasePublicationToSonatypeRepository
          :courier-core-android:publishReleasePublicationToSonatypeRepository
          :mqtt-pingsender:publishReleasePublicationToSonatypeRepository
          :workmanager-pingsender:publishReleasePublicationToSonatypeRepository
          :workmanager-2.6.0-pingsender:publishReleasePublicationToSonatypeRepository
          :alarm-pingsender:publishReleasePublicationToSonatypeRepository
          :timer-pingsender:publishReleasePublicationToSonatypeRepository
          :adaptive-keep-alive:publishReleasePublicationToSonatypeRepository
          :network-tracker:publishReleasePublicationToSonatypeRepository
          :courier-message-adapter-text:publishReleasePublicationToSonatypeRepository
          :courier-message-adapter-gson:publishReleasePublicationToSonatypeRepository
          :courier-message-adapter-moshi:publishReleasePublicationToSonatypeRepository
          :courier-message-adapter-protobuf:publishReleasePublicationToSonatypeRepository
          :courier-stream-adapter-rxjava:publishReleasePublicationToSonatypeRepository
          :courier-stream-adapter-rxjava2:publishReleasePublicationToSonatypeRepository
          :courier-stream-adapter-coroutines:publishReleasePublicationToSonatypeRepository
          :app-state-manager:publishReleasePublicationToSonatypeRepository
          :mqtt-client:publishReleasePublicationToSonatypeRepository
          :courier-auth-http:publishReleasePublicationToSonatypeRepository
          :courier:publishReleasePublicationToSonatypeRepository
          :chuck-mqtt:publishReleasePublicationToSonatypeRepository
          :chuck-mqtt-no-ops:publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
